[package]
name = "panther"
version = "0.1.0"
authors = ["Ramachandra Bhaskar Ayalavarapu <ramachandra.bhaskar@fireeye.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
